### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by ghost** [jkchen2/JshBot#1]
Hi @jkchen2 

Loving your bot `JshBot` creating my own bot for dicord game chat of mine.

Was wondering can I use some of your source? If I can what credits would you like me to provide for you?

**Comment by jkchen2** [comment]
Sure thing. JshBot is under the MIT license, so if you plan on using a large portion of the code, be sure to include the MIT license with it.

**Comment by ghost** [comment]
@jkchen2 Thanks bud

**Comment by ghost** [comment]
@jkchen2 I have a stupid question If I use a large portion how does the MIT work if I also have a MIT licence? Because my MIT states

```
MIT License

Copyright (c) 2016 di48l069
```

and yours states

```
The MIT License (MIT)

Copyright (c) 2016 jkchen2
```

Which one do I use lol

**Comment by jkchen2** [comment]
Sorry for the late reply. I believe using yours is just fine.

**Comment by ghost** [comment]
Thanks man for your response
